on:
  pull_request:
    types:
      - closed

jobs:
  stable_website_cherry_pick:
    if: github.event.pull_request.merged && contains(github.event.pull_request.labels.*.name, 'docs-cherrypick')
    runs-on: ubuntu-latest
    name: Cherry pick to stable-website branch
    steps:
    - name: Checkout
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        ref: stable-website
    - run: |
        git fetch --no-tags --prune origin main
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git cherry-pick ${{ github.sha }}
        git push origin stable-website
