name: Tests

on: [push, workflow_dispatch]

jobs:
  fmtcheck:
    runs-on: ubuntu-latest
    env:
      GOFUMPT_VERSION: 0.3.1
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
        with:
          go-version-file: .go-version
          cache: true
      - run: |
          go install "mvdan.cc/gofumpt@v${GOFUMPT_VERSION}"
          make fmtcheck

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
        with:
          go-version-file: .go-version
          cache: true
      - run: make test

  integrationTest:
    runs-on: ubuntu-latest
    needs: [fmtcheck, test]
    strategy:
      fail-fast: false
      matrix:
        kind-k8s-version: [1.22.15, 1.23.13, 1.24.7, 1.25.3, 1.26.2]
        enterprise: ["", "-ent"]
    name: Integration test ${{ matrix.enterprise }} kind ${{ matrix.kind-k8s-version }}
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Create K8s Kind Cluster
        uses: helm/kind-action@d8ccf8fb623ce1bb360ae2f45f323d9d5c5e9f00 # v1.5.0
        with:
          version: v0.17.0
          cluster_name: vault-plugin-secrets-kubernetes
          config: integrationtest/kind/config.yaml
          node_image: kindest/node:v${{ matrix.kind-k8s-version }}
          kubectl_version: v1.25.3
      - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
        with:
          go-version-file: .go-version
          cache: true
      - env:
          VAULT_LICENSE_CI: ${{ secrets.VAULT_LICENSE_CI }}
        run: make setup-integration-test${{ matrix.enterprise }}
      - env:
          INTEGRATION_TESTS: true
        run: make integration-test TESTARGS="-v"
